version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    expose:
      - "3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/walnut-and-clack
      - NEXTAUTH_URL=https://walnut.kmilicic.dev
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
    depends_on:
      - db
    networks:
      - nginx-proxy
      - internal

  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=walnut-and-clack
    expose:
      - "5432"
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - internal

networks:
  nginx-proxy:
    external: true
  internal:
    driver: bridge

volumes:
  db:
    driver: local
