version: "3.8"
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=walnut-and-clack
    ports:
      - "5432:5432"
    volumes:
      - db-dev:/var/lib/postgresql/data

volumes:
  db-dev:
    driver: local
